Repository Cazoo-uk/action-lockbot, pull requests merged in 2022-07, with the labels that each got.

#1 LIST-1067: Lockbot acquire
  .github/workflows/lint.yml
  .github/workflows/release.yml
  action.yml
Labels: size/L

#2 Changed permissions
  .github/workflows/release.yml
Labels: size/XS

#3 Added readme
  README.md
Labels: size/XS, major

#6 [NI] Testing contents write v2
  README.md
Labels: size/XS, release:major

#7 [NI] Improve readme
  README.md
  action.yml
Labels: size/XS

#8 [NI] Improving readme v2
  README.md
Labels: size/XS, release:patch

#11 List 1067 fix 2
  action.yml
Labels: release:patch, size/S

#12 [NI] Release functionality
  README.md
  action.yml
Labels: size/M

#13 [NI] Release func v2
  action.yml
Labels: size/S

#14 [NI] Release func v3
  action.yml
Labels: size/S

#15 [NI] Release func v4
  action.yml
Labels: size/XS

#16 fixed bug
  action.yml
Labels: size/XS
